import React,{useState,useEffect,useMemo,useRef} from 'react';
import {Play,MagicWand,Check,CircleNotch} from '@phosphor-icons/react';
import {wordGroups} from './studio-helpers.mjs';
const fmt=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toFixed(2).padStart(5,'0')}`;

export function Transcript({words,time,onSeek,onEdit,frameWords}){
 const [mode,setMode]=useState('sentence'),[expanded,setExpanded]=useState(null);
 const groups=useMemo(()=>wordGroups(words,mode==='sentence'?28:frameWords,mode==='sentence'?10:100),[words,mode,frameWords]);
 return <><div className="transcript-modes"><button className={mode==='sentence'?'active':''} onClick={()=>setMode('sentence')}>Theo câu</button><button className={mode==='frame'?'active':''} onClick={()=>setMode('frame')}>Theo khung phụ đề</button></div><p className="helper">Bấm câu hoặc mốc thời gian để nghe lại. Mở “Sửa chữ” để chỉnh từng từ và giữ nguyên nhịp karaoke.</p><div className="sentence-editor">{groups.map((g,i)=><article className={time>=g[0].start&&time<g.at(-1).end?'speaking':''} key={g[0].start}><header><button onClick={()=>onSeek(g[0].start)}>{fmt(g[0].start)} → {fmt(g.at(-1).end)}</button><span>{g[0].speaker||'Lời thoại'}</span></header><p>{g.map((w,j)=><React.Fragment key={j}><button className={time>=w.start&&time<w.end?'word-active':''} onClick={()=>onSeek(w.start)}>{w.text}</button>{' '}</React.Fragment>)}</p><button className="edit-sentence" onClick={()=>setExpanded(expanded===i?null:i)}>{expanded===i?'Xong':'Sửa chữ'}</button>{expanded===i&&<div className="inline-word-edit">{g.map((w,j)=><label key={j}><small>{fmt(w.start)}</small><input aria-label={'Từ tại '+w.start+' giây'} value={w.text} style={{width:Math.max(6,w.text.length+2)+'ch'}} onChange={e=>onEdit(w,e.target.value)}/></label>)}</div>}</article>)}</div></>;
}
export function TextControls({prefix,label,settings,onChange,Slider}){
 return <details className="text-controls"><summary>{label} · kiểu chữ & vị trí</summary><label className="field"><span>Màu chữ {label.toLowerCase()}</span><input aria-label={'Màu chữ '+label} type="color" value={settings[prefix+'_color']} onChange={e=>onChange(prefix+'_color',e.target.value)}/></label><Slider label={'Cỡ chữ '+label} min={28} max={prefix==='intro'?100:110} step={2} value={settings[prefix+'_size']} format={v=>v+' px'} onChange={v=>onChange(prefix+'_size',v)}/><Slider label={'Vị trí ngang '+label} min={.1} max={.9} value={settings[prefix+'_x']} onChange={v=>onChange(prefix+'_x',v)}/><Slider label={'Vị trí dọc '+label} min={.12} max={prefix==='intro'?.8:.83} value={settings[prefix+'_y']} onChange={v=>onChange(prefix+'_y',v)}/><Slider label={'Độ rộng '+label} min={.3} max={.9} value={settings[prefix+'_width']} onChange={v=>onChange(prefix+'_width',v)}/></details>;
}
export function VoiceControls({settings,onChange,post,notify,media}){
 const [working,setWorking]=useState(''),[plan,setPlan]=useState(null),[spoken,setSpoken]=useState(''),[audio,setAudio]=useState(null);
 const generation=useRef(0);
 useEffect(()=>{generation.current++;setPlan(null);setSpoken('');setAudio(null);},[settings.intro_text,settings.intro_voice]);
 async function run(key,fn){setWorking(key);const token=generation.current;try{await fn(()=>token===generation.current);}catch(e){notify(e.message,true);}finally{setWorking('');}}
 async function listen(sample){await run(sample?'sample':'listen',async current=>{const result=await post('/tts/preview',{voice:settings.intro_voice,...(sample?{}:{text:settings.intro_text,approval_id:settings.intro_approval_id})});if(current())setAudio(result.path);});}
 return <div className="voice-controls"><p className="helper">Giọng dựng sẵn của Google. Nút nghe mẫu đọc: “Chào mừng bạn đến với công cụ cắt video tự động bằng AI của MISA”.</p><div className="voice-buttons"><button className="secondary small" disabled={!!working} onClick={()=>listen(true)}>{working==='sample'?<CircleNotch className="spin"/>:<Play/>}Nghe mẫu giọng</button><button className="secondary small" disabled={!!working||!settings.intro_text.trim()} onClick={()=>listen(false)}>{working==='listen'?<CircleNotch className="spin"/>:<Play/>}Nghe lời mở đầu</button></div>{audio&&<audio key={audio} controls autoPlay src={media(audio)}/>}<button className="secondary small full" disabled={!!working||!settings.intro_text.trim()} onClick={()=>run('normalize',async current=>{const p=await post('/tts/normalize',{text:settings.intro_text});if(current()){setPlan(p);setSpoken(p.tts_text);}})}><MagicWand/>Kiểm tra cách đọc theo quy ước</button>{plan&&<div className="tts-review"><span className="tiny-label">BẢN CHỈ DÙNG ĐỂ ĐỌC · {plan.pronunciation_dictionary_version}</span><textarea aria-label="Bản đọc TTS" value={spoken} onChange={e=>setSpoken(e.target.value)} rows={5}/>{plan.warnings.length>0&&<p className="tts-warning">Cần kiểm tra: {plan.warnings.join(', ')}. Bạn có thể sửa cách đọc ở trên; chữ trên video vẫn giữ nguyên.</p>}<details><summary>{plan.spans.length} mục trong lịch sử chuẩn hóa</summary>{plan.spans.map((s,i)=><p key={i}>{s.original} → {s.normalized} <small>{s.category} · {s.rule_id}</small></p>)}</details><button className="primary small full" disabled={!!working||!spoken.trim()} onClick={()=>run('approve',async current=>{const result=await post('/tts/approve',{text:settings.intro_text,tts_text:spoken});if(current()){onChange('intro_approval_id',result.id);notify('Đã duyệt cách đọc. Bấm Lưu để dùng cho bản dựng.');}})}><Check/>Dùng bản đọc này</button></div>}{settings.intro_approval_id&&<p className="helper"><Check/>Đã duyệt bản đọc cho lời mở đầu hiện tại.</p>}</div>;
}

export function IntroCanvas({clip,post,media,moveText,notify}){
 const [card,setCard]=useState(null);
 const signature=JSON.stringify([clip.id,clip.title,clip.settings]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{post(`/clips/${clip.id}/intro-preview`,{title:clip.title,summary:clip.summary,start:clip.start,end:clip.end,settings:clip.settings,words:[]}).then(r=>active&&setCard(r)).catch(e=>active&&notify(e.message,true));},180);return()=>{active=false;clearTimeout(timer);};},[signature]);
 return <div className="intro-preview">{card?<><img className="intro-rendered" src={media(card.path)} alt="Xem trước intro với lời mở đầu và tiêu đề clip"/>{card.layers.map(layer=><div key={layer.prefix} className="intro-drag-handle" role="button" tabIndex={0} aria-label={layer.prefix==='intro'?'Di chuyển lời mở đầu':'Di chuyển tiêu đề clip'} title="Kéo để di chuyển · chỉnh chính xác bằng thanh vị trí" style={{left:layer.x*100+'%',top:layer.y*100+'%',width:layer.width*100+'%',height:layer.height*100+'%'}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>moveText(e,layer.prefix)}/> )}</>:<span className="intro-loading">Đang cập nhật khung intro…</span>}</div>;
}
