import React,{useEffect,useState} from 'react';

export function PresetBar({clip,api,post,notify,onApply}){
 const [items,setItems]=useState([]),[id,setId]=useState(''),[name,setName]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const reload=()=>api('/presets').then(setItems);
 useEffect(()=>{reload().catch(e=>notify(e.message,true));},[]);
 async function run(fn){setBusy(true);try{await fn();}catch(e){notify(e.message,true);}finally{setBusy(false);}}
 return <div className="preset-bar"><div className="preset-select"><select aria-label="Preset thiết lập" value={id} onChange={e=>setId(e.target.value)}><option value="">Chọn preset của kênh…</option>{items.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!id||busy} onClick={()=>run(async()=>{const r=await post('/presets/'+id+'/apply',clip.settings);await onApply(r.settings);notify('Đã áp dụng preset. Bấm Lưu để giữ thiết lập cho clip này.');})}>Áp dụng</button><button aria-expanded={open} onClick={()=>setOpen(!open)}>Lưu preset</button></div>{open&&<div className="preset-editor"><input aria-label="Tên preset" placeholder="Ví dụ: MISA News · Talk dọc" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><div className="preset-actions"><button disabled={!name.trim()||busy} onClick={()=>run(async()=>{const p=await post('/presets',{name:name.trim(),settings:clip.settings});await reload();setId(p.id);setName('');notify('Đã lưu preset để dùng cho các video khác.');})}>Lưu thành preset mới</button><button disabled={!id||busy} onClick={()=>run(async()=>{const p=items.find(p=>p.id===id);await api('/presets/'+id,{method:'PUT',body:JSON.stringify({name:p.name,settings:clip.settings})});await reload();notify('Đã cập nhật preset đã chọn.');})}>Cập nhật preset đã chọn</button><button disabled={!id||busy} onClick={()=>run(async()=>{await api('/presets/'+id,{method:'DELETE'});setId('');await reload();notify('Đã xóa preset; thiết lập trên clip vẫn giữ nguyên.');})}>Xóa preset</button></div><p>Gồm bố cục intro, giọng đọc, phụ đề, AI focus, Mix, watermark, nhạc và outro. Lời dẫn, tiêu đề, ảnh nhân vật và đoạn cắt giữ riêng cho từng clip.</p></div>}</div>;
}
